### ISSUE TITLE
Question about the worlds

### ISSUE THREAD

**Issue by ZetherDev** [Mezy/UhcCore#65]
What are the names of the generated maps?

**Comment by BelKed** [comment]
I think you mean _world_ instead of _map_.
This plugin generates world named randomly as "a3f028f8-068d-4d1a-8afe-8c5c80dc8811".
Also, you could find it's name in launch log.
For example: `[18:36:34 INFO]: [UhcCore] Creating new world : a3f028f8-068d-4d1a-8afe-8c5c80dc8811`.

**Comment by ZetherDev** [comment]
> nicio.

Exactly, that was it!
But do you know how I can change those names?

**Comment by ZetherDev** [comment]
And another question, I am using this plugin to create worlds and I pass them to another server .. it only generates a piece of map (500x500) while the other generates another type of world ..

**Comment by BelKed** [comment]
> But do you know how I can change those names?

You can change world name to be permanent  in "config.yml" located in `/plugins/UhcCore/config.yml`.
There is line in config:
```yaml
permanent-world-names: false
```
which you should change to:
```yaml
permanent-world-names: false
```
This will make, that world name will be always "uhc-normal".
Also, it is not suggested because, it may couse some worlds to not load correctly.
I don't think, that you can change it. But, it will be nice feature.

**Comment by BelKed** [comment]
> And another question, I am using this plugin to create worlds and I pass them to another server .. it only generates a piece of map (500x500) while the other generates another type of world ..

If you want to change size of world (world border – default is 500x500), you can look in "config.yml".
There is that line:
```yaml
...
border:
  ...
  #Starting size of the border (500 means +500x, -500x, +500z, -500z)
  start-size: 500
...
```
You can change the value of "start-size" to size of world (world border), which you need.
Default Minecraft overworld world size is 30 000 000 x 30 000 000 x 256 blocks.
But, this is not suggested, because server will generate that large world very long time.

**Comment by ZetherDev** [comment]
> > And another question, I am using this plugin to create worlds and I pass them to another server .. it only generates a piece of map (500x500) while the other generates another type of world ..
> 
> If you want to change size of world (world border – default is 500x500), you can look in "config.yml".
> There is that line:
> 
> ```yaml
> ...
> border:
>   ...
>   #Starting size of the border (500 means +500x, -500x, +500z, -500z)
>   start-size: 500
> ...
> ```
> 
> You can change the value of "start-size" to size of world (world border), which you need.
> Default Minecraft overworld world size is 30 000 000 x 30 000 000 x 256 blocks.
> But, this is not suggested, because server will generate that large world very long time.

Man, thank you very much, really thank you very much <3

I will close the issue
